# Generated by Django 3.1.5 on 2021-01-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mani',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_title', to='booking.extra'),
        ),
    ]
