# Generated by Django 3.1.5 on 2021-01-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_mani_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='extra',
            field=models.CharField(choices=[('PLN', 'Peeling'), ('ENT', 'Entfernung fremder Gele oder Shellac'), ('NGL', 'Nagellack'), ('SHL', 'Shellac'), ('SLF', 'Shellac French'), ('AZP', 'Augenbraunen zupfen'), ('AFR', 'Augenbraunen färben'), ('WFR', 'Wimpern färben'), ('OLE', 'Oberlippen Enthaarung'), ('ACE', 'Achsel Enthaarung'), ('KNE', 'Enthaarung der Beine bis zum Knie'), ('BEE', 'Enthaarung der ganzen Beine'), ('RUE', 'Enthaarung des Rückens oder Brust')], max_length=64),
        ),
        migrations.AlterField(
            model_name='mani',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.extra'),
        ),
    ]
