# Generated by Django 3.1.5 on 2021-01-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210122_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mani',
            name='extra',
        ),
    ]
