# Generated by Django 3.1.5 on 2021-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_mani_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='relation',
            field=models.CharField(choices=[('M', 'M'), ('P', 'P'), ('K', 'K')], default='M', max_length=1),
        ),
    ]
