# Generated by Django 3.1.5 on 2021-01-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_extra_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='relation',
            field=models.CharField(choices=[('M', 'M'), ('P', 'P'), ('K', 'K')], max_length=1),
        ),
    ]
