# Generated by Django 3.1.5 on 2021-01-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210123_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.duration')),
            ],
        ),
    ]
